### ISSUE TITLE
Update the documentation to the up-to-date state

### ISSUE THREAD

**Issue by SimonBrandner** [matrix-org/waterfall#35]
- Update README.
- Describe how to deploy the service.
- Describe how to monitor its events.

**Comment by daniel-abramov** [comment]
I'm closing this issue in favor of https://github.com/matrix-org/waterfall/issues/39 since the README has been updated according to the new dockerized workflow and the deployment pipeline should probably not be documented here as currently, only the members of the repository can deploy things manually. Whereas the documentation of code is part of a linked issue.
