### ISSUE TITLE
Ending screen-sharing doesn't generate a new SDP offer being send to other clients

### ISSUE THREAD

**Issue by SimonBrandner** [matrix-org/waterfall#68]
1. Have a call with two clients (A and B)
2. A start screen-sharing
3. A stops screen-sharing
4. B sees stuck screen-sharing feed which isn't changing
5. A leaves the call
6. B sees both feeds disappear

**Comment by daniel-abramov** [comment]
This happens because we only receive an `Unpublish` command from A. It seems like something has changed in the EC and/or js-sdk for that matter. Previously `Unpublish` was immediately followed by `Publish`, that's why it worked about a week ago or so, but apparently something changed.

Anyway, I decided to "fix" it by treating `Unpublish` as `Publish` (as they are identical in this regard?). This seems to fix the issue.
